# -*- coding: utf-8 -*-
"""generate numbers from 0000000000 to 9999999999.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zBheV0gXFChVCo-ix5nOARnKENsHfveJ
"""

filename = 'numbers.txt'

# เปิดไฟล์สำหรับเขียน (สร้างไฟล์ใหม่หรือเขียนทับทับไฟล์ที่มีอยู่)
with open(filename, 'w') as file:
    for i in range(999): #10000000000
        # จัดรูปแบบเลขให้อยู่ในรูปแบบสตริง 10 หลักพร้อมเติมเลข 0 ข้างหน้า
        number = str(i).zfill(10)

        # เขียนเลขที่ผ่านการจัดรูปแบบลงในไฟล์
        file.write(number + '\n')

print(f'สร้างเลขและบันทึกลงใน {filename} เสร็จสิ้น')